# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGeTdHtteSoa78G-_vvAMhn6Em77m5c-
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

# ----------------------------
# Page Configuration
# ----------------------------
st.set_page_config(
    page_title="Iris K-Means Clustering",
    page_icon="🌸",
    layout="wide"
)

st.title("🌸 Iris Flower Clustering using K-Means")

st.write("""
This application performs **K-Means Clustering** on the Iris dataset
using only:

- Petal Length
- Petal Width
""")

# ----------------------------
# Load Dataset
# ----------------------------
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["Species"] = iris.target

# Keep only required features
data = df[["petal length (cm)", "petal width (cm)"]]

st.subheader("Dataset")

st.dataframe(data.head(10))

# ----------------------------
# Scaling Option
# ----------------------------
st.sidebar.header("Settings")

scale = st.sidebar.checkbox("Apply Min-Max Scaling", value=True)

X = data.copy()

if scale:
    scaler = MinMaxScaler()
    X = pd.DataFrame(
        scaler.fit_transform(X),
        columns=X.columns
    )

# ----------------------------
# Select K
# ----------------------------
k = st.sidebar.slider(
    "Select Number of Clusters (K)",
    2,
    9,
    3
)

# ----------------------------
# KMeans
# ----------------------------
model = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

clusters = model.fit_predict(X)

X["Cluster"] = clusters

# ----------------------------
# Scatter Plot
# ----------------------------
st.subheader("Cluster Visualization")

fig, ax = plt.subplots(figsize=(7,6))

colors = [
    "red",
    "blue",
    "green",
    "orange",
    "purple",
    "brown",
    "pink",
    "cyan",
    "black"
]

for i in range(k):
    cluster = X[X["Cluster"] == i]

    ax.scatter(
        cluster["petal length (cm)"],
        cluster["petal width (cm)"],
        color=colors[i],
        label=f"Cluster {i}"
    )

# Cluster Centers
centers = model.cluster_centers_

ax.scatter(
    centers[:,0],
    centers[:,1],
    marker="X",
    s=250,
    color="black",
    label="Centroids"
)

ax.set_xlabel("Petal Length")

ax.set_ylabel("Petal Width")

ax.legend()

st.pyplot(fig)

# ----------------------------
# Cluster Centers
# ----------------------------
st.subheader("Cluster Centers")

center_df = pd.DataFrame(
    centers,
    columns=["Petal Length", "Petal Width"]
)

st.dataframe(center_df)

# ----------------------------
# Elbow Plot
# ----------------------------
st.subheader("Elbow Method")

sse = []

k_range = range(1,10)

for i in k_range:
    km = KMeans(
        n_clusters=i,
        random_state=42,
        n_init=10
    )
    km.fit(X.drop("Cluster", axis=1))
    sse.append(km.inertia_)

fig2, ax2 = plt.subplots(figsize=(7,5))

ax2.plot(
    list(k_range),
    sse,
    marker="o"
)

ax2.set_xlabel("Number of Clusters (K)")
ax2.set_ylabel("SSE")
ax2.set_title("Elbow Plot")

st.pyplot(fig2)

st.success("Optimal K from the elbow graph is approximately **3**.")

# ----------------------------
# Clustered Dataset
# ----------------------------
st.subheader("Clustered Dataset")

result = data.copy()
result["Cluster"] = clusters

st.dataframe(result)