# -*- coding: utf-8 -*-
"""knnproj8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18U4Zp4OowqnkdNvcTubl3cHhdzEn6ee7
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# --------------------------------------------------
# PAGE CONFIGURATION
# --------------------------------------------------

st.set_page_config(
    page_title="Iris Flower Classification",
    page_icon="🌸",
    layout="wide"
)

# --------------------------------------------------
# CUSTOM CSS
# --------------------------------------------------

st.markdown("""
<style>

.stApp{
background:linear-gradient(135deg,#EEF5FF,#FFFFFF,#F5FAFF);
}

#MainMenu{visibility:hidden;}
footer{visibility:hidden;}
header{visibility:hidden;}

.title{
text-align:center;
font-size:42px;
font-weight:bold;
color:#1565C0;
}

.subtitle{
text-align:center;
font-size:18px;
color:#555;
margin-bottom:25px;
}

.card{
background:white;
padding:20px;
border-radius:15px;
box-shadow:0px 4px 15px rgba(0,0,0,0.12);
margin-bottom:20px;
}

[data-testid="stMetric"]{
background:white;
padding:12px;
border-radius:12px;
box-shadow:0px 2px 10px rgba(0,0,0,0.08);
}

.stButton>button{
background:#1565C0;
color:white;
font-size:17px;
font-weight:bold;
border-radius:10px;
padding:10px;
width:100%;
}

</style>
""", unsafe_allow_html=True)

# --------------------------------------------------
# TITLE
# --------------------------------------------------

st.markdown("""
<div class="title">
🌸 Iris Flower Classification using KNN
</div>

<div class="subtitle">
Predict the species of an Iris flower using the K-Nearest Neighbors Machine Learning algorithm.
</div>
""", unsafe_allow_html=True)

st.divider()

# --------------------------------------------------
# LOAD DATASET
# --------------------------------------------------

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["Species"] = iris.target

species_names = iris.target_names

# --------------------------------------------------
# MODEL
# --------------------------------------------------

X = df.drop("Species", axis=1)
y = df["Species"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=1
)

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

accuracy = knn.score(X_test, y_test) * 100

# --------------------------------------------------
# METRICS
# --------------------------------------------------

m1, m2, m3 = st.columns(3)

with m1:
    st.metric("Dataset Size", len(df))

with m2:
    st.metric("Features", 4)

with m3:
    st.metric("Model Accuracy", f"{accuracy:.2f}%")

st.divider()

# --------------------------------------------------
# USER INPUT
# --------------------------------------------------

st.subheader("🌼 Enter Flower Measurements")

col1, col2 = st.columns(2)

with col1:

    sepal_length = st.slider(
        "Sepal Length (cm)",
        4.0,
        8.0,
        5.1
    )

    sepal_width = st.slider(
        "Sepal Width (cm)",
        2.0,
        4.5,
        3.5
    )

with col2:

    petal_length = st.slider(
        "Petal Length (cm)",
        1.0,
        7.0,
        1.4
    )

    petal_width = st.slider(
        "Petal Width (cm)",
        0.1,
        2.5,
        0.2
    )

if st.button("🔍 Predict Species"):

    sample = pd.DataFrame(
        [[
            sepal_length,
            sepal_width,
            petal_length,
            petal_width
        ]],
        columns=X.columns
    )

    prediction = knn.predict(sample)[0]

    st.success(
        f"🌸 Predicted Species: **{species_names[prediction].title()}**"
    )

st.divider()

# --------------------------------------------------
# DATASET
# --------------------------------------------------

with st.expander("📄 View Iris Dataset"):

    st.dataframe(
        df,
        use_container_width=True
    )
    # --------------------------------------------------
# CORRELATION HEATMAP
# --------------------------------------------------

st.subheader("📊 Correlation Heatmap")

corr = df.corr(numeric_only=True)

fig1, ax1 = plt.subplots(figsize=(3.5,2.5))

sns.heatmap(
    corr,
    annot=True,
    cmap="Blues",
    linewidths=0.5,
    ax=ax1
)

st.pyplot(fig1)

st.divider()

# --------------------------------------------------
# CONFUSION MATRIX
# --------------------------------------------------

st.subheader("📈 Confusion Matrix")

pred = knn.predict(X_test)

cm = confusion_matrix(y_test, pred)

fig2, ax2 = plt.subplots(figsize=(3.5,2.5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=species_names,
    yticklabels=species_names,
    ax=ax2
)

ax2.set_xlabel("Predicted Label")
ax2.set_ylabel("Actual Label")

st.pyplot(fig2)

st.divider()

# --------------------------------------------------
# CLASS DISTRIBUTION
# --------------------------------------------------

st.subheader("🌸 Species Distribution")

fig3, ax3 = plt.subplots(figsize=(3.5,2.5))

counts = df["Species"].value_counts().sort_index()

ax3.bar(
    species_names,
    counts,
    color=["#4CAF50", "#2196F3", "#FF9800"]
)

ax3.set_ylabel("Count")

st.pyplot(fig3)

st.divider()

# --------------------------------------------------
# MODEL PERFORMANCE
# --------------------------------------------------

st.subheader("📋 Model Performance")

c1, c2 = st.columns(2)

with c1:

    st.metric(
        "Accuracy",
        f"{accuracy:.2f}%"
    )

with c2:

    st.metric(
        "Training Samples",
        len(X_train)
    )

st.success(
    "The K-Nearest Neighbors (KNN) classifier achieved excellent performance on the Iris dataset."
)

st.divider()

# --------------------------------------------------
# ABOUT PROJECT
# --------------------------------------------------

st.markdown("""
<div class='card'>

<h3 style='color:#1565C0;'>📖 About the Project</h3>

This application predicts the species of an Iris flower using the
<b>K-Nearest Neighbors (KNN)</b> machine learning algorithm.

<b>Workflow</b>

<ul>
<li>Load Iris Dataset</li>
<li>Train KNN Classifier</li>
<li>Accept Flower Measurements</li>
<li>Predict Flower Species</li>
<li>Visualize Model Performance</li>
</ul>

<b>Predicted Classes</b>

<ul>
<li>🌸 Setosa</li>
<li>🌼 Versicolor</li>
<li>🌺 Virginica</li>
</ul>

</div>
""", unsafe_allow_html=True)

st.divider()

# --------------------------------------------------
# TECHNOLOGIES USED
# --------------------------------------------------

st.subheader("🛠 Technologies Used")

t1, t2, t3, t4 = st.columns(4)

with t1:
    st.metric("Language", "Python")

with t2:
    st.metric("ML Model", "KNN")

with t3:
    st.metric("Framework", "Scikit-learn")

with t4:
    st.metric("Frontend", "Streamlit")

st.divider()

# --------------------------------------------------
# FOOTER
# --------------------------------------------------

st.markdown("""
<div style='text-align:center;color:gray;'>

### 🌸 Iris Flower Classification using KNN

Built with ❤️ using Python • Streamlit • Scikit-learn • Pandas • NumPy • Matplotlib • Seaborn

</div>
""", unsafe_allow_html=True)
