# -*- coding: utf-8 -*-
"""eyepredictioncnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17F84AXWv0m4Rg-oxa10nyVJceRiWqCIZ
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="AI Eye Gender Detector",
    page_icon="👁️",
    layout="centered"
)

# -----------------------------
# Custom CSS
# -----------------------------
st.markdown("""
<style>

.stApp{
    background: linear-gradient(to right,#eef2ff,#f8fbff);
}

/* Main title */
.title{
    text-align:center;
    font-size:45px;
    color:#1f4e79;
    font-weight:bold;
}

/* Subtitle */
.subtitle{
    text-align:center;
    color:#555;
    font-size:18px;
    margin-bottom:25px;
}

/* Card */
.card{
    background:white;
    padding:25px;
    border-radius:18px;
    box-shadow:0px 8px 20px rgba(0,0,0,0.12);
    margin-top:20px;
}

/* Prediction */
.prediction{
    text-align:center;
    font-size:32px;
    font-weight:bold;
    color:#0f4c81;
}

/* Confidence */
.conf{
    text-align:center;
    color:#444;
    font-size:20px;
}

/* Footer */
.footer{
    text-align:center;
    color:gray;
    font-size:15px;
    margin-top:35px;
}

</style>
""", unsafe_allow_html=True)

# -----------------------------
# Load Model
# -----------------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("male_female_eye_model.keras")

model = load_model()

IMG_SIZE = (128,128)

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.title("👁️ About Project")

st.sidebar.write("""
### AI Eye Gender Detection

This application predicts whether an eye belongs to a:

- 👨 Male
- 👩 Female

### Technology

- TensorFlow
- Keras CNN
- Streamlit
- NumPy
- Pillow

Developed by **Aamina Hasan**
""")

# -----------------------------
# Title
# -----------------------------
st.markdown("<div class='title'>👁️ AI Eye Gender Detector</div>", unsafe_allow_html=True)

st.markdown(
"<div class='subtitle'>Upload a clear image of one eye to let AI predict the gender.</div>",
unsafe_allow_html=True)

# -----------------------------
# Upload Image
# -----------------------------
uploaded_file = st.file_uploader(
    "Upload Eye Image",
    type=["jpg","jpeg","png"]
)

# -----------------------------
# Prediction
# -----------------------------
if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(
        image,
        caption="Uploaded Image",
        use_container_width=True
    )

    img = image.resize(IMG_SIZE)
    img = np.array(img)/255.0
    img = np.expand_dims(img,axis=0)

    prediction = model.predict(img)[0][0]

    if prediction > 0.5:
        label = "👨 Male Eye"
        confidence = prediction
    else:
        label = "👩 Female Eye"
        confidence = 1-prediction

    st.markdown("<div class='card'>", unsafe_allow_html=True)

    st.markdown(
        f"<div class='prediction'>{label}</div>",
        unsafe_allow_html=True
    )

    st.write("")

    st.progress(float(confidence))

    st.markdown(
        f"<div class='conf'>Confidence : {confidence*100:.2f}%</div>",
        unsafe_allow_html=True
    )

    st.write("")

    st.subheader("Prediction Probability")

    st.bar_chart({
        "Probability":[
            float(1-prediction),
            float(prediction)
        ]
    })

    st.markdown("</div>", unsafe_allow_html=True)

# -----------------------------
# Footer
# -----------------------------
st.markdown(
"""
<div class='footer'>
Made with ❤️ using TensorFlow & Streamlit
</div>
""",
unsafe_allow_html=True
)